### ISSUE TITLE
수정된 모임정보의 경우 수정된 정보로 출력되지 않는 문제

### ISSUE THREAD

**Issue by Kitchu0401** [Kitchu0401/lazecrew-batch-service#3]
id 기준으로 비교하여 기 등록된 모임일 경우 db에 입력하지 않기 때문
- 단순하게 기 저장 여부 체크 후 신규 추출된 모임만 입력하는 로직에서 `upsert`로 변경해야하며
- 최초 등록된 정보에서 변경된 모임에 대하여 사용자에게 안내하기 위한 정책을 결정해야 함
    (1) 수정된 모임 정보는 메시지 발신 대상에서 제외하거나
    (2) 수정되었음을 알리거나

**Comment by Kitchu0401** [comment]
현재까지 관찰한 바
1. 자동으로 입력되는 제목 `ㅇㅇㅇ님이 YYYY년 MM월 DD일에 등록한 모임 등` 과 함께 **최초 모임 정보가 등록**되고
2. 이후 **제목을 수정**하는 경우가 발생함
3. 1. 의 과정에서 `title` 과 매칭을 시도하지만 대개 무의미한 `title` 이므로 사용자에게 알림이 가지 않고,
    2. 의 과정에서 올바른 `title` 로 변경되지만 기 등록된 document 이므로 신규 모임 정보 목록에서 제외됨.
4. 따라서
    - 1. 의 과정에서 `title` 매칭 뿐 아니라 `abstract` 또는 `content` 매칭까지 고려하고
        - `content` 매칭을 지원하는 경우 퍼포먼스를 항시 주시해야하며
        - 사용자에게 전달되는 알림 메시지 내에서 별도로 일치하는 `content` 에 대한 정보를 제공해야 할 것
    - 2. 의 과정에서 기 등록된 document 와 비교하여 `tite` 이 상이할 경우 추가로 알림을 보내도록 함

**Comment by pureugong** [comment]
@Kitchu0401 
I checked all events which created on this month, 2017-06. It turns out **there are around 50 ~ 150 new events created every day, and it is usually 1-2 weeks before event date**

So you can calculate how often and how many pages you need to call their API. (kinda QPS)

 116 2017-06-01
  86 2017-06-02
  23 2017-06-03
  40 2017-06-04
  90 2017-06-05
  51 2017-06-06
 122 2017-06-07
 109 2017-06-08
  98 2017-06-09
  35 2017-06-10
  36 2017-06-11
 165 2017-06-12
 105 2017-06-13
 109 2017-06-14
 126 2017-06-15
  43 2017-06-16

- max diff reg_date event_date : 356
- min diff reg_date event_date : 0
- avg diff reg_date event_date : 16.66

- % of <= 7 days : 25%
- % of <= 14 days : 57%
- % of <= 21 days : 78%
- % of <= 30 days : 91%
- % of <= 60 days : 98%
- % of <= 90 days : 99%

**Comment by Kitchu0401** [comment]
First of all thx for the data! : )

Well I've never considered about approaching with real time-based data and certainly it is interesting.
When I determined task interval, I wanted to make sure never missed event that I wanted to take part in.
You know, well-known meetup or events are tend to be full SO early, and I missed several times lol.

Yeah honestly I want to make interval shorten. But there's always performance issue, and I have a plan to add more source from various type of event - concert, show, what can be else? I'm noob at this lol - gradually, so maybe have to compomise moderately.

_OR BUY A BETTER MACHINE_

+ at least we can apply dynamic interval based on time-table
+ sooo hard to write long sentences in Eng even though borrowing hands from GT.

Used any tool to extract it btw? :nerd_face:
